package com.qurion.businesslogic.application.model;
// Generated Mar 26, 2014 10:43:34 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EntityDataExclude generated by hbm2java
 */
@Entity
@Table(name="ENTITY_DATA_EXCLUDE"
    ,catalog="businesslogic"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODE") 
)
public class EntityDataExclude  implements java.io.Serializable {


     private Integer id;
     private Universe universeByExcludeUniverseId;
     private Universe universeByUniverseId;
     private EntityData entityData;
     private String code;
     private String name;
     private String description;
     private Date effectiveDt;
     private char recSt;
     private Integer versionNo;
     private Date rowTs;
     private Date createdDt;
     private String createdByUsr;
     private Date lastModifiedDt;
     private String lastModifiedUsr;

    public EntityDataExclude() {
    }

	
    public EntityDataExclude(Universe universeByExcludeUniverseId, Universe universeByUniverseId, EntityData entityData, String code, String name, Date effectiveDt, char recSt, Date createdDt, String createdByUsr) {
        this.universeByExcludeUniverseId = universeByExcludeUniverseId;
        this.universeByUniverseId = universeByUniverseId;
        this.entityData = entityData;
        this.code = code;
        this.name = name;
        this.effectiveDt = effectiveDt;
        this.recSt = recSt;
        this.createdDt = createdDt;
        this.createdByUsr = createdByUsr;
    }
    public EntityDataExclude(Universe universeByExcludeUniverseId, Universe universeByUniverseId, EntityData entityData, String code, String name, String description, Date effectiveDt, char recSt, Integer versionNo, Date rowTs, Date createdDt, String createdByUsr, Date lastModifiedDt, String lastModifiedUsr) {
       this.universeByExcludeUniverseId = universeByExcludeUniverseId;
       this.universeByUniverseId = universeByUniverseId;
       this.entityData = entityData;
       this.code = code;
       this.name = name;
       this.description = description;
       this.effectiveDt = effectiveDt;
       this.recSt = recSt;
       this.versionNo = versionNo;
       this.rowTs = rowTs;
       this.createdDt = createdDt;
       this.createdByUsr = createdByUsr;
       this.lastModifiedDt = lastModifiedDt;
       this.lastModifiedUsr = lastModifiedUsr;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EXCLUDE_UNIVERSE_ID", nullable=false)
    public Universe getUniverseByExcludeUniverseId() {
        return this.universeByExcludeUniverseId;
    }
    
    public void setUniverseByExcludeUniverseId(Universe universeByExcludeUniverseId) {
        this.universeByExcludeUniverseId = universeByExcludeUniverseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNIVERSE_ID", nullable=false)
    public Universe getUniverseByUniverseId() {
        return this.universeByUniverseId;
    }
    
    public void setUniverseByUniverseId(Universe universeByUniverseId) {
        this.universeByUniverseId = universeByUniverseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ENTITY_DATA_ID", nullable=false)
    public EntityData getEntityData() {
        return this.entityData;
    }
    
    public void setEntityData(EntityData entityData) {
        this.entityData = entityData;
    }

    
    @Column(name="CODE", unique=true, nullable=false, length=75)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="NAME", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DT", nullable=false, length=10)
    public Date getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Date effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    
    @Column(name="REC_ST", nullable=false, length=1)
    public char getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(char recSt) {
        this.recSt = recSt;
    }

    
    @Column(name="VERSION_NO")
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ROW_TS", length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DT", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    
    @Column(name="CREATED_BY_USR", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_MODIFIED_DT", length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    
    @Column(name="LAST_MODIFIED_USR", length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }




}


